//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public System.DateTime IssuedAt { get; set; }
        public int RegistrationPlateId { get; set; }
        public int VehicleId { get; set; }
    
        public virtual RegistrationPlate RegistrationPlate { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
