//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSchedule
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public System.DateTime ScheduledFor { get; set; }
        public int ServiceTypeId { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
